# Generated by Django 6.0.3 on 2026-03-12 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeteranProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=20, unique=True)),
                ('rank', models.CharField(choices=[('sepoy', 'Sepoy'), ('naik', 'Naik'), ('havildar', 'Havildar'), ('subedar', 'Subedar'), ('subedar_major', 'Subedar Major'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lt_colonel', 'Lt. Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier'), ('major_general', 'Major General'), ('lt_general', 'Lt. General'), ('general', 'General')], max_length=30)),
                ('regiment', models.CharField(blank=True, max_length=200)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_retirement', models.DateField(blank=True, null=True)),
                ('home_state', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('disability_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veteran_profiles',
            },
        ),
    ]
