# Generated by Django 6.0.3 on 2026-03-12 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('discharge_certificate', 'Discharge Certificate'), ('service_record', 'Service Record'), ('medical_certificate', 'Medical Certificate'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('bank_details', 'Bank Details'), ('pension_ppo', 'Pension PPO'), ('photo', 'Photograph')], max_length=50)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=200)),
                ('ipfs_hash', models.CharField(blank=True, max_length=200)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
